### PR TITLE
Removed ticket price before ticket availability

### LINKED ISSUE #7: Main page shows wrong ticket price if there are no seatable tickets
Currently since the ticket sale hasn't started and there aren't any seatable ticket types the smallest ticket price defaults to the value of Number.MAX_SAFE_INTEGER (which is really goofy btw why the hell is it done this way lol)

Suggestions are to either not display the price at all before the ticket sale has begun so we make sure the ticket types exist.
Or to simply change the default value to something more reasonable like 0 or display unknown price.

### PR DESCRIPTION
**Pull request by simsine**
This is just a suggestion for an easy solutionto close #7

### CODE REVIEW

**Comment by petterroea** [comment]
I suggest instead fixing the problem "properly" by not showing the ticket cost if there are no ticket types _or_ there are no _seatable_ tickets.

It can be implemented as an oneliner on this line using a filter: https://github.com/phoenixlan/phoenixmain-v1/blob/master/src/pages/Main.svelte#L105

**Comment by simsine** [comment]
Will do ty

**Comment by simsine** [comment]
Fixed and tested

**Review by bernes1 — COMMENTED** [review]
looks good 👍🏽

**Review by bernes1 — APPROVED** [review]

**Pull request merged**
